# Generated by Django 5.2.8 on 2025-11-22 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_id', models.CharField(max_length=64, verbose_name='Caller ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Client name')),
                ('client_type', models.CharField(blank=True, default='', max_length=32, verbose_name='Object type')),
                ('client_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('client_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Object URL')),
                ('is_consumed', models.BooleanField(default=False, verbose_name='Shown to user')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voip_incoming_calls', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Incoming call',
                'verbose_name_plural': 'Incoming calls',
                'ordering': ('-created_at',),
            },
        ),
    ]
