# Generated by Django 5.2.8 on 2025-11-22 10:13

import voip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0002_incomingcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoipSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ami_host', models.CharField(default=voip.models.ami_host_default, max_length=128, verbose_name='AMI host')),
                ('ami_port', models.PositiveIntegerField(default=voip.models.ami_port_default, verbose_name='AMI port')),
                ('ami_username', models.CharField(default=voip.models.ami_username_default, max_length=128, verbose_name='AMI username')),
                ('ami_secret', models.CharField(blank=True, default=voip.models.ami_secret_default, help_text='Stored in plain text in DB; restrict admin access.', max_length=255, verbose_name='AMI secret')),
                ('ami_use_ssl', models.BooleanField(default=voip.models.ami_ssl_default, verbose_name='AMI over SSL')),
                ('ami_connect_timeout', models.PositiveIntegerField(default=voip.models.ami_connect_timeout_default, verbose_name='AMI connect timeout, seconds')),
                ('ami_reconnect_delay', models.PositiveIntegerField(default=voip.models.ami_reconnect_delay_default, verbose_name='AMI reconnect delay, seconds')),
                ('incoming_enabled', models.BooleanField(default=voip.models.incoming_enabled_default, verbose_name='Show incoming pop-ups')),
                ('incoming_poll_interval_ms', models.PositiveIntegerField(default=voip.models.incoming_poll_default, verbose_name='Polling interval, ms')),
                ('incoming_popup_ttl_ms', models.PositiveIntegerField(default=voip.models.incoming_ttl_default, verbose_name='Popup duration, ms')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VoIP settings',
                'verbose_name_plural': 'VoIP settings',
            },
        ),
    ]
