# Generated by Rovo Dev
from django.db import migrations, models
from django.conf import settings


def get_default_base_url():
    return 'https://api2.onlinepbx.ru'

class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0003_voipsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePBXSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='OnlinePBX domain')),
                ('key_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Key ID')),
                ('key', models.CharField(blank=True, default='', max_length=255, verbose_name='Secret key')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API key (for auth)')),
                ('base_url', models.CharField(default=get_default_base_url, max_length=255, verbose_name='Base URL')),
                ('use_md5_base64', models.BooleanField(default=False, verbose_name='Content-MD5 as base64')),
                ('allowed_ip', models.CharField(blank=True, default='*', max_length=64, verbose_name='Allowed IP for webhooks')),
                ('webhook_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Webhook token')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OnlinePBX settings',
                'verbose_name_plural': 'OnlinePBX settings',
            },
        ),
    ]
