# Generated by Django 5.2.8 on 2025-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0004_onlinepbxsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.CharField(choices=[('Zadarma', 'Zadarma'), ('OnlinePBX', 'OnlinePBX')], help_text='Specify VoIP service provider', max_length=100, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='onlinepbxsettings',
            name='base_url',
            field=models.CharField(default='https://api2.onlinepbx.ru', max_length=255, verbose_name='Base URL'),
        ),
    ]
