# Generated by Django 5.1.7 on 2025-03-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_userprofile_pbx_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='subject',
            field=models.CharField(help_text='Briefly, what is this reminder about?', max_length=250, verbose_name='Subject'),
        ),
    ]
