# Generated by Django 6.0.3 on 2026-03-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_reminder_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='user_avatars/%Y/%m/%d/%H%M%S/', verbose_name='Avatar'),
        ),
    ]
