# Generated by Django 6.0.5 on 2026-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crm_email_notifications',
            field=models.BooleanField(default=True, help_text='Disabling will stop receiving emails from the CRM system.', verbose_name='CRM email notifications'),
        ),
    ]
