# Generated by Django 5.1.8 on 2025-04-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emlmessage',
            name='content',
            field=models.TextField(help_text="\nUse HTML. To specify the address of the embedded image, use {% cid_media ‘path/to/pic.png' %}.<br>\nYou can embed files uploaded to the CRM server in the ‘media/pics/’ folder.\n"),
        ),
        migrations.AlterField(
            model_name='signature',
            name='content',
            field=models.TextField(help_text="\nUse HTML. To specify the address of the embedded image, use {% cid_media ‘path/to/pic.png' %}.<br>\nYou can embed files uploaded to the CRM server in the ‘media/pics/’ folder.\n"),
        ),
    ]
