# Generated by Django 5.2.1 on 2025-06-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massmail', '0002_alter_emlmessage_content_alter_signature_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing', models.BooleanField(default=True, help_text='Allow mailing (formerly MAILING).')),
                ('emails_per_day', models.PositiveIntegerField(default=94, help_text='Maximum emails/day (formerly EMAILS_PER_DAY).')),
                ('use_business_time', models.BooleanField(default=False, help_text='Send only during business hours (formerly USE_BUSINESS_TIME).')),
                ('business_time_start', models.TimeField(default='08:30', help_text='Business hours start (formerly BUSINESS_TIME_START).')),
                ('business_time_end', models.TimeField(default='17:30', help_text='Business hours end (formerly BUSINESS_TIME_END).')),
                ('unsubscribe_url', models.URLField(default='https://www.example.com/unsubscribe', help_text='Unsubscribe redirect (formerly UNSUBSCRIBE_URL).', max_length=500)),
            ],
            options={
                'verbose_name': 'Massmail Settings',
                'verbose_name_plural': 'Massmail Settings',
            },
        ),
    ]
