# Generated by Django 6.0.5 on 2026-05-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massmail', '0002_alter_emlmessage_content_alter_signature_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emlmessage',
            name='content',
            field=models.TextField(help_text='Use HTML. To specify the address of the embedded image, use {% cid_media `path/to/pic.png` %}.<br>You can embed files uploaded to the CRM server in the `media/pics/` folder.'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='content',
            field=models.TextField(help_text='Use HTML. To specify the address of the embedded image, use {% cid_media `path/to/pic.png` %}.<br>You can embed files uploaded to the CRM server in the `media/pics/` folder.'),
        ),
    ]
