services:
  db:
    image: mysql:latest
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_DATABASE: 'crm_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'crm_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'crmpass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'crmpass'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
# Names our volume
volumes:
  my-db: