# Generated by Django 5.2.1 on 2025-06-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_per_day', models.PositiveIntegerField(default=94, help_text='Daily message limit for email accounts.')),
                ('use_business_time', models.BooleanField(default=False, help_text='Send only during business hours.')),
                ('business_time_start', models.TimeField(default='08:30', help_text='Start of working hours.')),
                ('business_time_end', models.TimeField(default='17:30', help_text='End of working hours.')),
                ('unsubscribe_url', models.URLField(default='https://www.example.com/unsubscribe', help_text='"Unsubscribed successfully" page."')),
            ],
            options={
                'verbose_name': 'Massmail Settings',
                'verbose_name_plural': 'Massmail Settings',
            },
        ),
    ]
