# Generated by Django 5.2.1 on 2025-05-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_currency_auto_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='skype',
        ),
    ]
