# Generated by Django 5.2.4 on 2025-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_contact_skype_remove_lead_skype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='District/County'),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Region/State'),
        ),
        migrations.AddField(
            model_name='contact',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='District/County'),
        ),
        migrations.AddField(
            model_name='contact',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Region/State'),
        ),
        migrations.AddField(
            model_name='lead',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='District/County'),
        ),
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Region/State'),
        ),
    ]
