# Generated by Django 6.0.5 on 2026-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_request_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='company_logos/%Y/%m/%d/%H%M%S/', verbose_name='Logo'),
        ),
    ]
