# Generated by Django 5.2.8 on 2025-11-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_request_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='sla_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override default first-response SLA hours for this source.', null=True, verbose_name='SLA hours'),
        ),
    ]
