# Generated by Django 6.0.5 on 2026-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='contact_avatars/%Y/%m/%d/%H%M%S/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='lead',
            name='avatar',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='contact_avatars/%Y/%m/%d/%H%M%S/', verbose_name='Avatar'),
        ),
    ]
