# Generated by Django 6.0.6 on 2026-08-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_contact_avatar_lead_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='product_images/%Y/%m/%d/%H%M%S/', verbose_name='Main image'),
        ),
    ]
