# Generated by Django 6.0.7 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='utm_source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='UTM source'),
        ),
        migrations.AddField(
            model_name='request',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='UTM medium'),
        ),
        migrations.AddField(
            model_name='request',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='UTM campaign'),
        ),
        migrations.AddField(
            model_name='request',
            name='utm_term',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='UTM term'),
        ),
        migrations.AddField(
            model_name='request',
            name='utm_content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='UTM content'),
        ),
        migrations.AddField(
            model_name='request',
            name='gclid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Google click ID'),
        ),
        migrations.AddField(
            model_name='request',
            name='fbclid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook click ID'),
        ),
    ]
