# Generated by Django 6.0.7 on 2026-09-09 10:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0013_request_attribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='tier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tier_name_related', to='crm.clienttype', verbose_name='Price tier'),
        ),
        migrations.CreateModel(
            name='CategoryPriceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('F', 'Fixed Price'), ('D', 'Discount percentage'), ('M', 'Markup percentage')], max_length=1, verbose_name='Price type')),
                ('base_tier', models.BooleanField(default=False, help_text='Indicates whether this price level is the base tier for calculating other tiers in the department.', verbose_name='Base tier')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='The percentage of discount or markup relative to the base tier.', max_digits=5, null=True, verbose_name='Percentage')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_category_related', to='crm.productcategory', verbose_name='Product Category')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('tier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tier_name_related', to='crm.clienttype', verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category Price Rule',
                'verbose_name_plural': 'Category Price Rules',
                'unique_together': {('tier_name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentPriceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('F', 'Fixed Price'), ('D', 'Discount percentage'), ('M', 'Markup percentage')], max_length=1, verbose_name='Price type')),
                ('base_tier', models.BooleanField(default=False, help_text='Indicates whether this price level is the base tier for calculating other tiers in the department.', verbose_name='Base tier')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='The percentage of discount or markup relative to the base tier.', max_digits=5, null=True, verbose_name='Percentage')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_department_related', to='auth.group', verbose_name='Department')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('tier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tier_name_related', to='crm.clienttype', verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Department Price Rule',
                'verbose_name_plural': 'Department Price Rules',
                'unique_together': {('tier_name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('min_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Quantity')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_department_related', to='auth.group', verbose_name='Department')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owner_related', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product', verbose_name='Product')),
                ('tier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tier_name_related', to='crm.clienttype', verbose_name='Tier Name')),
            ],
            options={
                'verbose_name': 'Product Price Tier',
                'verbose_name_plural': 'Product Price Tiers',
                'unique_together': {('tier_name', 'product')},
            },
        ),
    ]
