# Generated by Django 6.0.7 on 2026-09-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_deal_tier_name_categorypricerule_departmentpricerule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('F', 'Fixed Price'), ('D', 'Discount percentage')], default='D', max_length=1, verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='deal',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Discount'),
        ),
    ]
