# Generated by Django 5.2.8 on 2026-01-02 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0009_request_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionQualitySignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('weight', models.SmallIntegerField(help_text='A positive or negative integer reflecting the change in transaction quality.', verbose_name='Weight (%)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_department_related', to='auth.group')),
            ],
            options={
                'verbose_name': 'Transaction-Quality Signal',
                'verbose_name_plural': 'Transaction-Quality Signals',
            },
        ),
        migrations.CreateModel(
            name='TransactionQualityEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(help_text='A positive or negative integer reflecting the change in transaction quality.', verbose_name='Weight (%)')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('details', models.TextField(blank=True, default='', verbose_name='Details')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.deal', verbose_name='Deal')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.transactionqualitysignal', verbose_name='Signal')),
            ],
            options={
                'verbose_name': 'Transaction-Quality Event',
                'verbose_name_plural': 'Transaction-Quality Events',
            },
        ),
    ]
