# Generated by Rovo Dev
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram')], db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('ig_app_id', models.CharField(blank=True, default='', max_length=255)),
                ('ig_app_secret', models.CharField(blank=True, default='', max_length=255)),
                ('ig_page_id', models.CharField(blank=True, default='', max_length=255)),
                ('ig_page_access_token', models.CharField(blank=True, default='', max_length=500)),
                ('ig_verify_token', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Channel account', 'verbose_name_plural': 'Channel accounts'},
        ),
        migrations.CreateModel(
            name='ExternalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('sender_id', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_id', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.channelaccount')),
            ],
            options={'verbose_name': 'External message', 'verbose_name_plural': 'External messages'},
        ),
    ]
