# Generated by Django 5.2.8 on 2025-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelaccount',
            name='playmobile_api_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='channelaccount',
            name='playmobile_auth_type',
            field=models.CharField(choices=[('basic', 'Login/Password'), ('token', 'Bearer Token')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='channelaccount',
            name='playmobile_status_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='channelaccount',
            name='playmobile_token',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
